---
name: homelab

services:
  jellyfin:
    image: jellyfin/jellyfin:12.0
    container_name: jellyfin
    restart: always
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - ./media/movies:/media/movies:ro
      - ./media/tv:/media/tv:ro
    environment:
      JELLYFIN_PublishedServerUrl: ${BASE_URL}
    networks:
      - homelab

networks:
  homelab:
    external: true
